[tool.poetry]
name = "webassn3"
version = "0.1.0"
description = ""
authors = ["Noah Call <a02361280@aggies.usu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
